#!/usr/bin/env node
/*
 * Fills the generated parts of index.html (English) and index.pt.html
 * (Portuguese) from the reference data:
 *
 *  1. Citation lists: <span data-cite-list="QUERY"></span> gets a list of
 *     citation links for every reference matching QUERY. The prose around it
 *     is hand-written; the lists only follow from the data.
 *       QUERY   = clause ("|" clause)*          any clause may match
 *       clause  = term (" " term)*              all terms must match
 *       term    = tag=a,b | group=a | insertion=a | id=a,b   (write spaces in values as +)
 *  2. Inline citations: every <a class="cite" data-cite="id">…</a> gets its
 *     label regenerated from the data, e.g. "(Niu et al., 2026a)".
 *  3. The reading list between the readings markers: rows of
 *     content/readings.csv marked approved=yes, ranked by citation count
 *     (content/citations.json, from scripts/update-citations.py).
 *  4. The bibliography between the references markers, listing every cited
 *     entry and the section(s) citing it.
 *
 *   node scripts/build-page.js          rewrite both pages
 *   node scripts/build-page.js --check  exit 1 if either page is out of date
 *
 * Fails if the page cites an id that is not in the reference data.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const READINGS_FILE = path.join(ROOT, 'content', 'readings.csv');
const CITATIONS_FILE = path.join(ROOT, 'content', 'citations.json');
const READINGS_START = '<!-- readings:start (generated by scripts/build-page.js from content/readings.csv; do not edit) -->';
const READINGS_END = '<!-- readings:end -->';
const PAGES = [
  {
    file: 'index.html', lang: 'en', locale: 'en-US', citedIn: 'Cited in',
    readingsPending: 'The curated list is being reviewed and will appear here soon.',
    citationCount: '{n} citations',
    readingsLabel: 'Reading list, ranked by citations (scrollable)',
    citationSource: 'Citation counts: {source}, retrieved {date}.',
    groups: {
      fundamentals: 'Foundations',
      'cycle-skipping': 'Cycle-skipping and misfit functions',
      multiparameter: 'Multiparameter inversion and crosstalk',
      'deep-learning': 'Deep learning in FWI',
      uncertainty: 'Uncertainty',
      'time-lapse': 'Time-lapse monitoring',
    },
  },
  {
    file: 'index.pt.html', lang: 'pt', locale: 'pt-BR', citedIn: 'Citado em',
    readingsPending: 'A lista curada está em revisão e aparecerá aqui em breve.',
    citationCount: '{n} citações',
    readingsLabel: 'Lista de leituras, ordenada por citações (com rolagem)',
    citationSource: 'Contagem de citações: {source}, consulta em {date}.',
    groups: {
      fundamentals: 'Fundamentos',
      'cycle-skipping': 'Cycle-skipping e funções de misfit',
      multiparameter: 'Inversão multiparâmetro e crosstalk',
      'deep-learning': 'Deep learning no FWI',
      uncertainty: 'Incerteza',
      'time-lapse': 'Monitoramento time-lapse',
    },
  },
];
const READING_COLUMNS = ['id', 'group', 'source', 'approved', 'review', 'sentence_en', 'sentence_pt'];
const DATA_FILES = ['assets/data/foundational-references.json', 'assets/data/literature.json'];
const START = '<!-- references:start (generated by scripts/build-page.js; do not edit) -->';
const END = '<!-- references:end -->';
const SECTION_PATTERN = /<details class="section" id="([^"]+)">\s*<summary><h2 class="section-title">(.*?)<\/h2>/g;
const CITE_LIST_PATTERN = /(<span class="cite-list" data-cite-list="([^"]+)">)[\s\S]*?(<\/span>)/g;
const INLINE_CITE_PATTERN = /<a class="cite" href="#([^"]+)" data-cite="\1">[^<]*<\/a>/g;
const CITE_PATTERN = /data-cite="([^"]+)"/g;

function escapeHtml(text) {
  return String(text).replace(/[&<>"]/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
  });
}

// ------------------------------------------------------------------- data

function loadReferences() {
  const byId = new Map();
  DATA_FILES.forEach(function (file) {
    const data = JSON.parse(fs.readFileSync(path.join(ROOT, file), 'utf8'));
    data.references.forEach(function (ref) {
      ['id', 'authors', 'year', 'title', 'venue'].forEach(function (key) {
        if (!ref[key]) throw new Error(file + ': reference ' + (ref.id || '?') + ' is missing "' + key + '"');
      });
      if (byId.has(ref.id)) throw new Error('duplicate reference id: ' + ref.id);
      byId.set(ref.id, Object.assign({ tags: [], group: 'foundational', insertion: null }, ref));
    });
  });
  assignLabels(byId);
  return byId;
}

function surname(author) {
  return author.split(',')[0].trim();
}

// "(Niu et al., 2026a)"-style labels, with letters when author+year repeat.
function assignLabels(byId) {
  const groups = new Map();
  byId.forEach(function (ref) {
    const a = ref.authors;
    const who = a.length === 1 ? surname(a[0])
      : a.length === 2 ? surname(a[0]) + ' & ' + surname(a[1])
      : surname(a[0]) + ' et al.';
    const base = who + ', ' + ref.year;
    groups.set(base, (groups.get(base) || []).concat(ref));
  });
  groups.forEach(function (refs, base) {
    refs.sort(function (x, y) { return x.title.localeCompare(y.title); });
    refs.forEach(function (ref, i) {
      ref.yearLabel = String(ref.year) + (refs.length > 1 ? String.fromCharCode(97 + i) : '');
      ref.label = base.replace(/\d{4}$/, ref.yearLabel);
    });
  });
}

// --------------------------------------------------------- citation lists

function matchesTerm(ref, term) {
  const [key, value] = term.split('=');
  const wanted = (value || '').split(',').map(function (v) { return v.replace(/\+/g, ' '); });
  if (key === 'tag') return wanted.some(function (t) { return ref.tags.includes(t); });
  if (key === 'group') return wanted.includes(ref.group);
  if (key === 'insertion') return wanted.includes(ref.insertion);
  if (key === 'id') return wanted.includes(ref.id);
  throw new Error('unknown cite-list term: ' + term);
}

function selectRefs(refs, query) {
  const clauses = query.split('|').map(function (c) { return c.trim().split(/\s+/); });
  const out = Array.from(refs.values()).filter(function (ref) {
    return clauses.some(function (terms) { return terms.every(function (t) { return matchesTerm(ref, t); }); });
  });
  if (out.length === 0) throw new Error('cite-list matched nothing: ' + query);
  return out.sort(function (a, b) { return a.year - b.year || a.label.localeCompare(b.label); });
}

function citeLink(ref, className, text) {
  return '<a class="' + className + '" href="#' + ref.id + '" data-cite="' + ref.id + '">' + escapeHtml(text) + '</a>';
}

function fillCitations(html, refs) {
  const withLists = html.replace(CITE_LIST_PATTERN, function (all, open, query, close) {
    const items = selectRefs(refs, query).map(function (ref) { return citeLink(ref, 'cite-item', ref.label); });
    return open + '(' + items.join('; ') + ')' + close;
  });
  return withLists.replace(INLINE_CITE_PATTERN, function (all, id) {
    const ref = refs.get(id);
    if (!ref) throw new Error('cited but not in reference data: ' + id);
    return citeLink(ref, 'cite', '(' + ref.label + ')');
  });
}

// ---------------------------------------------------------------- readings

// Minimal RFC 4180 parser: quoted fields, doubled quotes, commas and newlines inside quotes.
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') quoted = false;
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function loadReadings(refs, groups) {
  const [header, ...rows] = parseCsv(fs.readFileSync(READINGS_FILE, 'utf8'));
  if (header.join(',') !== READING_COLUMNS.join(',')) throw new Error('readings.csv: unexpected columns ' + header.join(','));
  return rows.filter(function (r) { return r.length > 1; }).map(function (r) {
    const row = Object.fromEntries(READING_COLUMNS.map(function (key, i) { return [key, (r[i] || '').trim()]; }));
    if (!refs.has(row.id)) throw new Error('readings.csv: unknown reference id ' + row.id);
    if (!groups[row.group]) throw new Error('readings.csv: unknown group ' + row.group + ' for ' + row.id);
    if (!['yes', 'no'].includes(row.approved)) throw new Error('readings.csv: approved must be yes or no for ' + row.id);
    return row;
  });
}

function loadCitations() {
  return JSON.parse(fs.readFileSync(CITATIONS_FILE, 'utf8'));
}

function localDate(iso, locale) {
  return new Date(iso + 'T12:00:00Z').toLocaleDateString(locale, { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' });
}

// Approved readings, most cited first (ties: newer first, then by id).
function rankedReadings(refs, groups, citations) {
  return loadReadings(refs, groups).filter(function (r) { return r.approved === 'yes'; }).map(function (r) {
    const count = citations.cited_by_count[r.id];
    if (!Number.isInteger(count)) throw new Error('citations.json: no count for ' + r.id + '; run scripts/update-citations.py');
    return Object.assign({ citations: count, year: refs.get(r.id).year }, r);
  }).sort(function (a, b) { return b.citations - a.citations || b.year - a.year || a.id.localeCompare(b.id); });
}

function fillReadings(html, refs, page) {
  const start = html.indexOf(READINGS_START);
  const end = html.indexOf(READINGS_END);
  if (start < 0 || end < start) return html; // page has no reading list
  const citations = loadCitations();
  const ranked = rankedReadings(refs, page.groups, citations);
  let body;
  if (ranked.length === 0) {
    body = '        <p class="placeholder">' + escapeHtml(page.readingsPending) + '</p>';
  } else {
    const items = ranked.map(function (r) {
      const count = page.citationCount.replace('{n}', r.citations.toLocaleString(page.locale));
      return '          <li><a class="cite" href="#' + r.id + '" data-cite="' + r.id + '"></a> ' +
        escapeHtml(r['sentence_' + page.lang]) +
        ' <span class="reading-meta">' + escapeHtml(count) + ' · ' + escapeHtml(page.groups[r.group]) + '</span></li>';
    });
    const note = page.citationSource.replace('{source}', citations.source)
      .replace('{date}', localDate(citations.retrieved, page.locale));
    // Scrollable box so the page can be read past the list; focusable for keyboard scrolling.
    body = '        <div class="reading-scroll" role="region" tabindex="0" aria-label="' + escapeHtml(page.readingsLabel) + '">\n' +
      '        <ol class="reading-list">\n' + items.join('\n') + '\n        </ol>\n        </div>\n' +
      '        <p class="note">' + escapeHtml(note) + '</p>';
  }
  return html.slice(0, start + READINGS_START.length) + '\n' + body + '\n        ' + html.slice(end);
}

// ----------------------------------------------------------- bibliography

function sectionsOf(html) {
  return Array.from(html.matchAll(SECTION_PATTERN)).map(function (m) {
    return { id: m[1], title: m[2], start: m.index };
  });
}

// id -> [{ id, title } of each section citing it], in page order.
function collectCitations(html) {
  const sections = sectionsOf(html);
  const bibStart = html.indexOf(START);
  const citedBy = new Map();
  for (const match of html.matchAll(CITE_PATTERN)) {
    if (match.index > bibStart && bibStart >= 0) continue;
    const section = sections.filter(function (s) { return s.start < match.index; }).pop();
    if (!section) throw new Error('citation ' + match[1] + ' is outside any section');
    const list = citedBy.get(match[1]) || [];
    if (!list.some(function (s) { return s.id === section.id; })) list.push({ id: section.id, title: section.title });
    citedBy.set(match[1], list);
  }
  return citedBy;
}

function formatEntry(ref, sections, citedInLabel) {
  const details = [ref.volume, ref.issue ? '(' + ref.issue + ')' : '', ref.pages ? ', ' + ref.pages : '']
    .join('').trim();
  const href = ref.doi ? 'https://doi.org/' + ref.doi : ref.link;
  const linkText = ref.doi ? 'doi:' + ref.doi : 'link';
  const link = href ? ' <a href="' + escapeHtml(href) + '">' + escapeHtml(linkText) + '</a>' : '';
  const citedIn = sections.map(function (s) { return '<a href="#' + s.id + '">' + s.title + '</a>'; }).join(', ');
  return [
    '          <li id="' + escapeHtml(ref.id) + '">',
    '            ' + escapeHtml(ref.authors.join(', ')) + ' (' + ref.yearLabel + '). ' + escapeHtml(ref.title) +
      '. <em>' + escapeHtml(ref.venue) + '</em>' + (details ? ' ' + escapeHtml(details) : '') + '.' + link,
    '            <span class="cited-on">' + citedInLabel + ': ' + citedIn + '</span>',
    '          </li>',
  ].join('\n');
}

function fillBibliography(html, refs, citedInLabel) {
  const citedBy = collectCitations(html);
  const missing = Array.from(citedBy.keys()).filter(function (id) { return !refs.has(id); });
  if (missing.length) throw new Error('cited but not in reference data: ' + missing.join(', '));
  const entries = Array.from(citedBy.keys()).map(function (id) { return refs.get(id); })
    .sort(function (a, b) { return a.authors[0].localeCompare(b.authors[0]) || a.yearLabel.localeCompare(b.yearLabel); });
  const list = '        <ol class="bibliography">\n' +
    entries.map(function (r) { return formatEntry(r, citedBy.get(r.id), citedInLabel); }).join('\n') + '\n        </ol>';
  const start = html.indexOf(START);
  const end = html.indexOf(END);
  if (start < 0 || end < start) throw new Error('page is missing the references markers');
  return html.slice(0, start + START.length) + '\n' + list + '\n        ' + html.slice(end);
}

// ------------------------------------------------------------------- main

function pageConfig(file) {
  const page = PAGES.find(function (p) { return p.file === file; });
  if (!page) throw new Error('unknown page: ' + file);
  return page;
}

function render(file) {
  const page = pageConfig(file || 'index.html');
  const refs = loadReferences();
  const html = fs.readFileSync(path.join(ROOT, page.file), 'utf8');
  return fillBibliography(fillCitations(fillReadings(html, refs, page), refs), refs, page.citedIn);
}

function main() {
  const check = process.argv.includes('--check');
  const stale = PAGES.filter(function (page) {
    const next = render(page.file);
    const target = path.join(ROOT, page.file);
    if (next === fs.readFileSync(target, 'utf8')) return false;
    if (!check) fs.writeFileSync(target, next);
    return true;
  });
  if (check && stale.length) {
    console.error(stale.map(function (p) { return p.file; }).join(', ') + ' out of date; run: node scripts/build-page.js');
    process.exit(1);
  }
}

if (require.main === module) main();
module.exports = {
  PAGES: PAGES, render: render, loadReferences: loadReferences, collectCitations: collectCitations,
  loadReadings: loadReadings, rankedReadings: rankedReadings, loadCitations: loadCitations, parseCsv: parseCsv,
};
